function Hd = myBandFilt
%MYBANDFILT 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 30-Jan-2021 23:40:14

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 14.6293;  % Sampling Frequency

N   = 2;    % Order
Fc1 = 0.2;  % First Cutoff Frequency
Fc2 = 1;    % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
